import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.scss'

const firaCode = localFont({
  src: './_ui/fonts/FiraCode-VF.woff2',
  variable: '--font-fira-code',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Creamy',
  description: 'Generated by NguyenDuy',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${firaCode.variable} antialiased`}>{children}</body>
    </html>
  )
}
