import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.scss'

import { Header } from '#_ui/layout'
import { NavBar } from './_ui/layout/nav'

const firaCode = localFont({
  src: './_ui/fonts/FiraCode-VF.woff2',
  variable: '--font-fira-code',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Creamy',
  description: 'Generated by NguyenDuy',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${firaCode.variable} antialiased`}>
        <Header />
        <NavBar />
        <div className="border-t"></div>
        <div className="mx-4">{children}</div>
      </body>
    </html>
  )
}
